export const SELECTED_COLUMNS_FOR_REPORT_OF_SALES = [
  'codeSale',
  'date',
  'departureDate',
  'client',
  'documentNumber',
  'documentType',
  'serviceName',
  'packageName',
  'quantity',
  'subtotal',
  'discount',
  'total',
  'status',
  'paymentMethod',
  'branch',
  'seller',
];

export const HEADERS_FOR_REPORT_OF_SALES = {
  codeSale: 'Código de Venta',
  date: 'Fecha',
  departureDate: 'Fecha de Salida',
  client: 'Cliente',
  documentNumber: 'Número de Documento',
  documentType: 'Tipo de Documento',
  serviceName: 'Servicio',
  packageName: 'Paquete',
  quantity: 'Cantidad',
  subtotal: 'Subtotal',
  discount: 'Descuento',
  total: 'Total',
  status: 'Estado',
  paymentMethod: 'Método de Pago',
  branch: 'Sucursal',
  seller: 'Vendedor',
  observations: 'Observaciones',
};
