export const CLIENT_TABLE_COLS = [ 
  	{field:'name', header:'Nombre', sortable:true},
  {field:'firstLastname', header:'Apellido Paterno', sortable:true},
  {field:'secondLastname', header:'Apellido Materno', sortable:true},
  {field:'phone', header:'Teléfono', sortable:true},
  {field:'email', header:'Correo Electrónico', sortable:true},
  {field:'typeDocument', header:'Tipo de Documento', sortable:true},
  {field:'numberDocument', header:'Número de Documento', sortable:true},
  {field:'birthDate', header:'Fecha de Nacimiento', sortable:true},
  { field: 'createdAt', header: 'Fecha de Creación', sortable: true },
  { field: 'updatedAt', header: 'Fecha de Modificación', sortable: true },
  {field:'registeredBy', header:'Registrado por', sortable:true},
  { field: 'status', header: 'Estado', sortable: true },
  { field: 'actions', header: 'Acciones', sortable: false },
];

// "name": "Juan",
// "firstLastname": "Pérez",
// "secondLastname": "García",
// "phone": "999888777",
// "email": "juan@email.com",
// "typeDocument": "DNI",
// "numberDocument": "12345678",
// "birthDate": "1990-01-01",
// "registeredBy": "string"